package com.mycompany.packagegenerator;

import javax.swing.JFileChooser;
import java.io.File;
import javax.swing.filechooser.FileNameExtensionFilter;
import com.mycompany.packagegenerator.SqlFileParser.TableInfo;
import java.awt.Color;
import com.mycompany.packagegenerator.ParseViewMenu;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kosugek
 */
public class HomeMenu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeMenu.class.getName());

    /**
     * Creates new form HomeMenu
     */
    public HomeMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public File getSqlFile() {
        return this.sqlFile;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        FileButton = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fileLabel = new javax.swing.JLabel();
        ParseButton = new java.awt.Button();
        generatePackageButton = new java.awt.Button();
        ShowParseButton = new java.awt.Button();
        ShowOutputButton = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 153));
        setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        setForeground(new java.awt.Color(255, 255, 255));
        setIconImages(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("PCDB Package Generator");

        FileButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        FileButton.setLabel("Choose File");
        FileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Filename:");

        fileLabel.setText("Null");

        ParseButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        ParseButton.setLabel("Parse File");
        ParseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParseButtonActionPerformed(evt);
            }
        });

        generatePackageButton.setActionCommand("Generate Package");
        generatePackageButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        generatePackageButton.setLabel("Generate Package");
        generatePackageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatePackageButtonActionPerformed(evt);
            }
        });

        ShowParseButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        ShowParseButton.setLabel("Show Parse");
        ShowParseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowParseButtonActionPerformed(evt);
            }
        });

        ShowOutputButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        ShowOutputButton.setLabel("Show SQL");
        ShowOutputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowOutputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ParseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(generatePackageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ShowParseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ShowOutputButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ParseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FileButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fileLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowParseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowOutputButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(generatePackageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select a file");
        //fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        // Optional: Set file filter
        fileChooser.setFileFilter(new FileNameExtensionFilter("SQL Files", "sql"));

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            sqlFile = selectedFile;
            System.out.println("file :" + selectedFile.getAbsolutePath());
            fileLabel.setText(selectedFile.getName());
            fileFound = true;
        }
    }//GEN-LAST:event_FileButtonActionPerformed

    private void ParseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParseButtonActionPerformed
        // TODO add your handling code here:
        try {
            SqlFileParser parser = new SqlFileParser();
            parser.parse(sqlFile.getAbsolutePath());
            for (SqlFileParser.TableInfo table : parser.getTables()) {//coul add more tables fix this
                tableinfo = table;
                System.out.print(table.toString());
            }
            ParseButton.setForeground(Color.green);
        } catch (Exception e) {
            ParseButton.setForeground(Color.red);
        }
    }//GEN-LAST:event_ParseButtonActionPerformed

    private void generatePackageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatePackageButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select a directory");
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); // This makes it select directories only

        int result = fileChooser.showOpenDialog(this);
        File selectedDirectory = null;

        if (result == JFileChooser.APPROVE_OPTION) {
            selectedDirectory = fileChooser.getSelectedFile();
        } else {
            selectedDirectory = null;
        }

        if (selectedDirectory == null) {
            System.out.println("No directory selected");
            return;
        }

        if (!selectedDirectory.isDirectory()) {
            System.out.println("Selected path is not a directory");
            return;
        }

        if (!selectedDirectory.canWrite()) {
            System.out.println("No write permission for selected directory");
            return;
        }

        if (ParseButton.getForeground() == Color.red) {
            System.out.println("error");
            return;
        }

        TableInfo current_tableinfo = this.tableinfo;
        PlsqlPackageGenerator generator = new PlsqlPackageGenerator(current_tableinfo);

        // Create the output file path
        String outputPath = selectedDirectory.getAbsolutePath() + File.separator + "p_" + current_tableinfo.tableName+".pck";
        generator.generatePackage(outputPath);
        System.out.print("Package generated in: " + outputPath);


    }//GEN-LAST:event_generatePackageButtonActionPerformed

    private void ShowParseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowParseButtonActionPerformed
        // TODO add your handling code here:
        ParseViewMenu pv = new ParseViewMenu();
        pv.setVisible(true);
        SqlFileParser.getUniqueColumns(tableinfo);


    }//GEN-LAST:event_ShowParseButtonActionPerformed

    private void ShowOutputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowOutputButtonActionPerformed
        // TODO add your handling code here:
        ShowSQLPanel sqlframe = new ShowSQLPanel();
        sqlframe.setVisible(true);
    }//GEN-LAST:event_ShowOutputButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeMenu().setVisible(true));
    }

    public File sqlFile;
    public Boolean fileFound = false;
    public TableInfo tableinfo = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button FileButton;
    private java.awt.Button ParseButton;
    private java.awt.Button ShowOutputButton;
    private java.awt.Button ShowParseButton;
    private javax.swing.JLabel fileLabel;
    private java.awt.Button generatePackageButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
